version: '3'

services:
  yourapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: my_module/app.py
      PORT: "5000"
    ports:
      - "5000:5000"
